-- Restored from supabase_migrations.schema_migrations.
-- This is the SQL the database records as having actually run, on 20260409021428.

-- Admin analytics (schema-aligned)
DO $$ BEGIN IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'investigations' AND column_name = 'ordered_at') THEN ALTER TABLE investigations ADD COLUMN ordered_at timestamptz DEFAULT now(); END IF; IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'investigations' AND column_name = 'resulted_at') THEN ALTER TABLE investigations ADD COLUMN resulted_at timestamptz; CREATE INDEX idx_investigations_tat ON investigations(ordered_at, resulted_at) WHERE resulted_at IS NOT NULL; END IF; END $$;
CREATE TABLE IF NOT EXISTS clinical_procedure_consents (consent_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), opd_encounter_id uuid REFERENCES opd_encounters(id), procedure_name text NOT NULL, signed_at timestamptz, created_at timestamptz DEFAULT now());
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_type WHERE typname = 'nabh_check_type') THEN CREATE TYPE nabh_check_type AS ENUM ('documentation_complete', 'consent_present', 'note_timeliness'); END IF; END $$;
CREATE TABLE IF NOT EXISTS nabh_compliance_checks (check_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hospital_id uuid NOT NULL, check_type nabh_check_type NOT NULL, department_id uuid, score_percentage numeric(5,2) NOT NULL, detail jsonb, last_calculated_at timestamptz DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_hospital_check ON nabh_compliance_checks(hospital_id, check_type, COALESCE(department_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS idx_nabh_compliance_hospital ON nabh_compliance_checks(hospital_id, check_type);
CREATE OR REPLACE FUNCTION get_avg_consultation_time(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_avg numeric; BEGIN SELECT AVG(EXTRACT(EPOCH FROM (checkout_time - checkin_time)) / 60) INTO v_avg FROM opd_encounters WHERE hospital_id = p_hospital_id AND checkin_time >= p_start_date AND checkin_time < p_end_date + 1 AND checkout_time IS NOT NULL; RETURN COALESCE(v_avg, 0); END;$$;
CREATE OR REPLACE FUNCTION get_avg_wait_time(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_avg numeric; BEGIN SELECT AVG(EXTRACT(EPOCH FROM (oe.checkin_time - a.check_in_time)) / 60) INTO v_avg FROM appointments a JOIN opd_encounters oe ON a.encounter_id = oe.id WHERE oe.hospital_id = p_hospital_id AND a.check_in_time >= p_start_date AND a.check_in_time < p_end_date + 1 AND a.check_in_time IS NOT NULL AND oe.checkin_time IS NOT NULL; RETURN COALESCE(v_avg, 0); END;$$;
CREATE OR REPLACE FUNCTION get_noshow_rate(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_rate numeric; BEGIN WITH stats AS (SELECT COUNT(*) FILTER (WHERE a.status = 'no_show') as ns, COUNT(*) as tot FROM appointments a JOIN opd_encounters oe ON a.encounter_id = oe.id WHERE oe.hospital_id = p_hospital_id AND a.appointment_date >= p_start_date AND a.appointment_date <= p_end_date AND a.status != 'cancelled') SELECT CASE WHEN tot > 0 THEN (ns::numeric / tot * 100) ELSE 0 END INTO v_rate FROM stats; RETURN COALESCE(v_rate, 0); END;$$;
CREATE OR REPLACE FUNCTION get_opd_utilization(p_hospital_id uuid, p_department_id uuid DEFAULT NULL, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_util numeric; v_enc int; v_cap int; BEGIN SELECT COUNT(*) INTO v_enc FROM opd_encounters WHERE hospital_id = p_hospital_id AND (p_department_id IS NULL OR department_id = p_department_id) AND checkin_time >= p_start_date AND checkin_time < p_end_date + 1; v_cap := EXTRACT(DAY FROM (p_end_date - p_start_date + 1)) * 32; v_util := CASE WHEN v_cap > 0 THEN (v_enc::numeric / v_cap * 100) ELSE 0 END; RETURN LEAST(v_util, 100); END;$$;
CREATE OR REPLACE FUNCTION get_operational_daily_metrics(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS TABLE (metric_date date, consultation_count integer, avg_wait_minutes numeric, avg_consult_minutes numeric) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN QUERY SELECT DATE(oe.checkin_time), COUNT(oe.id)::int, AVG(EXTRACT(EPOCH FROM (oe.checkin_time - a.check_in_time)) / 60), AVG(EXTRACT(EPOCH FROM (oe.checkout_time - oe.checkin_time)) / 60) FROM opd_encounters oe LEFT JOIN appointments a ON oe.id = a.encounter_id WHERE oe.hospital_id = p_hospital_id AND oe.checkin_time >= p_start_date AND oe.checkin_time < p_end_date + 1 GROUP BY DATE(oe.checkin_time) ORDER BY 1; END;$$;
CREATE OR REPLACE FUNCTION get_top_diagnoses(p_hospital_id uuid, p_specialty text DEFAULT NULL, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE, p_limit int DEFAULT 10) RETURNS TABLE (diagnosis_code text, diagnosis_name text, encounter_count int) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN QUERY SELECT d.snomed_code, d.description, COUNT(DISTINCT oe.id)::int FROM opd_encounters oe JOIN diagnoses d ON oe.id = d.encounter_id WHERE oe.hospital_id = p_hospital_id AND (p_specialty IS NULL OR oe.specialty = p_specialty) AND oe.checkin_time >= p_start_date AND oe.checkin_time < p_end_date + 1 GROUP BY d.snomed_code, d.description ORDER BY 3 DESC LIMIT p_limit; END;$$;
CREATE OR REPLACE FUNCTION get_prescription_patterns(p_hospital_id uuid, p_specialty text DEFAULT NULL, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE, p_limit int DEFAULT 10) RETURNS TABLE (medication_name text, prescription_count int, avg_duration_days numeric) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN QUERY SELECT m.medication_name, COUNT(*)::int, AVG(m.duration_days) FROM opd_encounters oe JOIN medications m ON oe.id = m.encounter_id WHERE oe.hospital_id = p_hospital_id AND (p_specialty IS NULL OR oe.specialty = p_specialty) AND oe.checkin_time >= p_start_date AND oe.checkin_time < p_end_date + 1 GROUP BY m.medication_name ORDER BY 2 DESC LIMIT p_limit; END;$$;
CREATE OR REPLACE FUNCTION get_investigation_tat(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_avg numeric; BEGIN SELECT AVG(EXTRACT(EPOCH FROM (i.resulted_at - i.ordered_at)) / 3600) INTO v_avg FROM investigations i JOIN opd_encounters oe ON i.encounter_id = oe.id WHERE oe.hospital_id = p_hospital_id AND i.ordered_at >= p_start_date AND i.ordered_at < p_end_date + 1 AND i.resulted_at IS NOT NULL; RETURN COALESCE(v_avg, 0); END;$$;
CREATE OR REPLACE FUNCTION get_avg_meds_per_encounter(p_hospital_id uuid, p_start_date date DEFAULT CURRENT_DATE - 30, p_end_date date DEFAULT CURRENT_DATE) RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_avg numeric; BEGIN WITH counts AS (SELECT oe.id, COUNT(m.medication_id) as cnt FROM opd_encounters oe LEFT JOIN medications m ON oe.id = m.encounter_id WHERE oe.hospital_id = p_hospital_id AND oe.checkin_time >= p_start_date AND oe.checkin_time < p_end_date + 1 GROUP BY oe.id) SELECT AVG(cnt) INTO v_avg FROM counts; RETURN COALESCE(v_avg, 0); END;$$;
CREATE OR REPLACE FUNCTION get_clinical_specialties_for_filter(p_hospital_id uuid) RETURNS TABLE (specialty text) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN QUERY SELECT DISTINCT oe.specialty FROM opd_encounters oe WHERE oe.hospital_id = p_hospital_id AND oe.specialty IS NOT NULL ORDER BY oe.specialty; END;$$;
CREATE OR REPLACE FUNCTION get_nabh_compliance_snapshot(p_hospital_id uuid) RETURNS TABLE (check_type nabh_check_type, department_id uuid, department_name text, score_percentage numeric, detail jsonb, last_calculated_at timestamptz) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN QUERY SELECT nc.check_type, nc.department_id, d.name, nc.score_percentage, nc.detail, nc.last_calculated_at FROM nabh_compliance_checks nc LEFT JOIN departments d ON nc.department_id = d.id WHERE nc.hospital_id = p_hospital_id ORDER BY nc.check_type, d.name NULLS FIRST; END;$$;
CREATE OR REPLACE FUNCTION refresh_nabh_compliance_for_hospital(p_hospital_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE v_doc numeric; v_con numeric; v_tim numeric; v_det jsonb; BEGIN WITH doc AS (SELECT COUNT(*) FILTER (WHERE chief_complaint IS NOT NULL AND hpi IS NOT NULL) c, COUNT(*) t FROM opd_encounters WHERE hospital_id = p_hospital_id AND checkin_time >= CURRENT_DATE - 30) SELECT CASE WHEN t > 0 THEN (c::numeric / t * 100) ELSE 100 END, jsonb_build_object('complete', c, 'total', t) INTO v_doc, v_det FROM doc; INSERT INTO nabh_compliance_checks (hospital_id, check_type, score_percentage, detail, last_calculated_at) VALUES (p_hospital_id, 'documentation_complete', v_doc, v_det, now()) ON CONFLICT ON CONSTRAINT idx_unique_hospital_check DO UPDATE SET score_percentage = EXCLUDED.score_percentage, detail = EXCLUDED.detail, last_calculated_at = EXCLUDED.last_calculated_at; WITH con AS (SELECT COUNT(DISTINCT cpc.opd_encounter_id) FILTER (WHERE cpc.signed_at IS NOT NULL) s, COUNT(DISTINCT cpc.opd_encounter_id) t FROM clinical_procedure_consents cpc JOIN opd_encounters oe ON cpc.opd_encounter_id = oe.id WHERE oe.hospital_id = p_hospital_id AND oe.checkin_time >= CURRENT_DATE - 30) SELECT CASE WHEN t > 0 THEN (s::numeric / t * 100) ELSE 100 END, jsonb_build_object('signed', s, 'total', t) INTO v_con, v_det FROM con; INSERT INTO nabh_compliance_checks (hospital_id, check_type, score_percentage, detail, last_calculated_at) VALUES (p_hospital_id, 'consent_present', v_con, v_det, now()) ON CONFLICT ON CONSTRAINT idx_unique_hospital_check DO UPDATE SET score_percentage = EXCLUDED.score_percentage, detail = EXCLUDED.detail, last_calculated_at = EXCLUDED.last_calculated_at; WITH tim AS (SELECT COUNT(*) FILTER (WHERE updated_at - checkin_time <= INTERVAL '24 hours') t, COUNT(*) tot FROM opd_encounters WHERE hospital_id = p_hospital_id AND checkin_time >= CURRENT_DATE - 30) SELECT CASE WHEN tot > 0 THEN (t::numeric / tot * 100) ELSE 100 END, jsonb_build_object('timely', t, 'total', tot) INTO v_tim, v_det FROM tim; INSERT INTO nabh_compliance_checks (hospital_id, check_type, score_percentage, detail, last_calculated_at) VALUES (p_hospital_id, 'note_timeliness', v_tim, v_det, now()) ON CONFLICT ON CONSTRAINT idx_unique_hospital_check DO UPDATE SET score_percentage = EXCLUDED.score_percentage, detail = EXCLUDED.detail, last_calculated_at = EXCLUDED.last_calculated_at; END;$$;
